name: package-test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  package-test:
    runs-on: ubuntu-latest
    name: package-test

    steps:
      - uses: actions/checkout@v5

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          coverage: none

      - name: Remove local path repository override
        run: composer config --unset repositories.0

      - run: composer update --prefer-dist --no-interaction --no-progress

      - run: vendor/bin/pest
